### ISSUE TITLE
White Screen after Install

### ISSUE THREAD

**Issue by ThyRaven13** [shrimpza/outofeve#26]
I've copied over the source files to my own server.  I've created a database for the user API's and installed the small SQL file you have with the source.  I'm using the evetools.info SQL server for the EVE Dump.  When I go to the page it is white.  Nothing will load.  I've tried enabling PHP errors but none of them display.  

http://voshun.bigracktech.com is the site.  Any ideas?

**Comment by shrimpza** [comment]
May I close this, since things may change with the upcoming version (and I assume nobody is attempting to use the current version anyway)?
