### ISSUE TITLE
Clean up UI

### ISSUE THREAD

**Issue by shrimpza** [shrimpza/outofeve#28]
A lot of the UI design looks very dated now, and should be cleaned up and enhanced significantly.

**Comment by shrimpza** [comment]
- Update menu icons to latest EVE graphics
- Maybe collapse left menu to just icons which expand their text on hover.

**Comment by ThyRaven13** [comment]
Last I knew Out Of Eve was discontinued. If you want changes made, fork it and get to work.

**Comment by shrimpza** [comment]
Erm, yes. That's exactly what I'm doing, sans the forking because I am the project owner.

**Comment by shrimpza** [comment]
I am using the issue tracker as a sort of TODO list at the moment. I apologise if it's causing noise in your inbox :|

**Comment by ThyRaven13** [comment]
Oops sorry.  Thought you were someone complaining.  I've been trying to figure out how to update OOE.  If you need any help, beta tester or Web space for development let me know.

On April 11, 2016 4:56:51 AM CDT, Kenneth Watson <notifications@github.com> wrote:
>I am using the issue tracker as a sort of TODO list at the moment. I
>apologise if it's causing noise in your inbox :|
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shrimpza/outofeve/issues/28#issuecomment-208263542

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shrimpza** [comment]
Cool.

I may need some more eyes on things once I get things up and running again, since my character is a bit behind in general, so I'm lacking a lot of data to test with.

I'll make an issue or something when that times comes so feedback can be gathered.
